.TH "RxBoxEngine::RxboxEngine" 3 "Fri May 20 2011" "Version v1.0" "This is a test project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RxBoxEngine::RxboxEngine \- 
.PP
RxBox Main Class.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBrun\fP"
.br
.ti -1c
.RI "def \fBchange_state\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdbuuid\fP"
.br
.ti -1c
.RI "\fBrxboxDB\fP"
.br
.ti -1c
.RI "\fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RxBox Main Class. 

.PP
.nf

    Engine/Controller class for Rxbox
    .fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def RxBoxEngine.RxboxEngine.change_state (self, state, args)".PP
.nf
Change state to state.fi
.PP
 
.SS "def RxBoxEngine.RxboxEngine.run (self)".PP
.nf

Run engine and start up GUI
.fi
.PP
 
.SH "Member Data Documentation"
.PP 
.SS "\fBRxBoxEngine.RxboxEngine.dbuuid\fP"
.SS "\fBRxBoxEngine.RxboxEngine.rxboxDB\fP"
.SS "\fBRxBoxEngine.RxboxEngine.state\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for This is a test project from the source code.
