.TH "p563.java" 3 "Fri May 20 2011" "Version v1.0" "This is a test project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
p563.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBp563\fP"
.br
.RI "\fIUVa problem 563 solution. \fP"
.ti -1c
.RI "class \fBp563.LL\fP"
.br
.ti -1c
.RI "class \fBp563.Edge\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for This is a test project from the source code.
