.TH "RxBoxEngine.py" 3 "Fri May 20 2011" "Version v1.0" "This is a test project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RxBoxEngine.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRxBoxEngine.RxboxEngine\fP"
.br
.RI "\fIRxBox Main Class. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBRxBoxEngine\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBRxBoxEngine.splash\fP"
.br
.RI "\fIThis is brief. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBRxBoxEngine.p\fP = Process(target=splash)"
.br
.RI "\fIsome variable \fP"
.ti -1c
.RI "tuple \fBRxBoxEngine.engine\fP = RxboxEngine()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for This is a test project from the source code.
